GET http://localhost:3000/

###
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}


###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWQiOiI3Y2Y3ZjM2NS1kYmE3LTQ2NzctOWJiOC0yZDAyODAxNDQ1NWQiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzExODU2MTMsImV4cCI6MTc3MTE4OTIxM30.ebLdq6NhJBwkCxmGzPaRgOeqHVL3VIhDWK0uZWTS-XE
