GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTQ4YTJlMC1mZmNiLTQwMTItOWUwYy0xMWZhM2Q2NzBhYTAiLCJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTc3Nzg0MTYyMCwiZXhwIjoxNzc3ODQ1MjIwfQ.6npCF8x8KaOadoYMCc8WmlLbhzTX0lxEvf4Dmugtnj8

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}


###
GET http://localhost:3000/users
Authorization: Bearer 
