### Listar Categorias
GET http://localhost:3000/cliente-proveedor


### Guardar
POST http://localhost:3000/cliente-proveedor
Content-Type: application/json

{
  "tipo": "proveedor",
  "razon_social": "ASUS SRL",
  "identificacion": "46546556",
  "telefono": "78822335",
  "direccion": "Av ABC",
  "correo": "asus@mail,com",
  "estado": true
}

### Mostrar por ID
GET http://localhost:3000/cliente-proveedor/2

### Editar por ID
PATCH http://localhost:3000/cliente-proveedor/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWQiOiJhNTQ4YTJlMC1mZmNiLTQwMTItOWUwYy0xMWZhM2Q2NzBhYTAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzE3NzU0MDEsImV4cCI6MTc3MTc3OTAwMX0.XNIv_N1kLDwZaNUY0xa5kiIzt4v4fuESJdEu6p2U6hs

{
    "nombre": "Electronicos",
    "descripcion": "Producto Electronico"
}

### Elininar por ID
DELETE http://localhost:3000/cliente-proveedor/2