### Listar Cliente Proveedor
GET http://localhost:3000/cliente-proveedor


### Guardar
POST http://localhost:3000/cliente-proveedor
Content-Type: application/json

{
  "tipo": "proveedor",
  "razon_social": "ASUS SRL",
  "identificacion": "46546556",
  "telefono": "78822335",
  "direccion": "Av ABC",
  "correo": "asus@mail,com",
  "estado": true
}

### Mostrar por ID
GET http://localhost:3000/cliente-proveedor/2

### Editar por ID
PATCH http://localhost:3000/cliente-proveedor/4
Content-Type: application/json

{
    "estado": true
}

### Elininar por ID
DELETE http://localhost:3000/cliente-proveedor/2