POST http://localhost:3000/nota
Content-Type: application/json
Accept: application/json

{
  "fecha": "2026-03-07",
  "tipo_nota": "venta",
  "cliente_id": 4,
  "user_id": "a548a2e0-ffcb-4012-9e0c-11fa3d670aa0",
  "estado_nota": "En Proceso",
  "observaciones": "Ninguna",
  "movimientos": [
    {
        "producto_id": 5,
        "almacen_id": 1,
        "cantidad": 1,
        "tipo_movimiento": "salida",
        "precio_unitario_compra": "0",
        "precio_unitario_venta": "20000.00",
        "observaciones": "ninguna"
    }
  ]
}

###
GET http://localhost:3000/nota