GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWQiOiI3Y2Y3ZjM2NS1kYmE3LTQ2NzctOWJiOC0yZDAyODAxNDQ1NWQiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzExODU2MTMsImV4cCI6MTc3MTE4OTIxM30.ebLdq6NhJBwkCxmGzPaRgOeqHVL3VIhDWK0uZWTS-XE

###
POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWQiOiI3Y2Y3ZjM2NS1kYmE3LTQ2NzctOWJiOC0yZDAyODAxNDQ1NWQiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzExODMyNTgsImV4cCI6MTc3MTE4MzMxOH0.yYar_f5KxgVE_B2wr2lNEHIat6BKpndBwAlTqOPUOAE

{
    "username": "Zilong",
    "email": "zilong@gmail.com",
    "password": "1234567890"
}